language: python
language: python
python:
- '3.6'
- '3.6-dev'
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- py.test --cov=`python3 -c "import json;print(json.load(open('Setup.lock'))['name'])"`
after_success:
- codecov
